// <auto-generated />
namespace Restaurante.Infraestructura.Datos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class primeraversion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(primeraversion));
        
        string IMigrationMetadata.Id
        {
            get { return "201904272006553_primera version"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
